/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#6f5100",
        "surface-tint": "#006a69",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#261900",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "on-primary-container": "#b6fffd",
        "tertiary-fixed-dim": "#adcec0",
        "primary": "#00605f",
        "on-background": "#1b1c1c",
        "secondary-container": "#fcc340",
        "on-surface": "#1b1c1c",
        "primary-fixed-dim": "#7ad5d4",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303030",
        "on-tertiary-container": "#d7f9eb",
        "secondary": "#795900",
        "outline-variant": "#bdc9c8",
        "surface": "#fbf9f8",
        "on-primary-fixed": "#002020",
        "outline": "#6e7979",
        "surface-bright": "#fbf9f8",
        "on-tertiary-fixed": "#012018",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-high": "#eae8e7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#96f2f0",
        "secondary-fixed-dim": "#f6be3b",
        "inverse-primary": "#7ad5d4",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3f0f0",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "on-surface-variant": "#3e4948",
        "surface-container": "#f0eded",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#c8eadc",
        "background": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "primary-container": "#007b7a",
        "tertiary": "#3d5c51",
        "tertiary-container": "#557469",
        "on-primary-fixed-variant": "#00504f",
        "on-secondary-fixed-variant": "#5c4300",
        "on-tertiary-fixed-variant": "#2f4d42",
        "secondary-fixed": "#ffdea0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
